services:
  lambda-dev:
    build:
      context: .
      dockerfile: docker/python3/Dockerfile
    env_file:
      - .env.dev
    ports:
      - "9001:9001"  
    command: ["python3", "/var/task/server.py"]
    environment:
      LAMBDA_ENV: dev

